[DEFAULT]
repo_dir = ~/dots
ignored_files = *.swp
age_identity = ~/.age/dots.key

[hostname1]
repo_dir = /data/dots
; ignored_files is inherited from DEFAULT section = *.swp,~*

[hostname2]
; repo_dir is inherited from DEFAULT section (value: '~/dots')
; ignored_files is inherited from DEFAULT section (value: '*.swp')

[hostname3]
; repo_dir is inherited from DEFAULT section (value: '~/dots')
ignored_files = *.swp,*.tmp
age_identity = ~/.age/dots-hostname3.key
