[DEFAULT]
repo_dir = ~/dots
ignored_files = *.swp

[hostname1]
repo_dir = /data/dots
; ignored_files is inherited from DEFAULT section = *.swp,~*

[hostname2]
; repo_dir is inherited from DEFAULT section (value: '~/dots')
; ignored_files is inherited from DEFAULT section (value: '*.swp')
